.github/workflows/versions.yml, .github/workflows/workflow.yml, dist/index.js, package-lock.json, package.json, src/installer.ts, src/main.ts
fix issue with cache dir (had spec instead of just version)
add bin to path 
fix audit issues
update tool-cache lib
Details:
This bin dir is an output dir when you build + install something in go.  So users want to call go build, go install and then run what they built.  This adds that output dir to the path.
hosted images and some folks install go but if they never did a build + install on a clean machine (hosted) it won’t exist.  That’s why I create it if (1) go is installed and (2) it doesn’t exist
To avoid fragility I exec go env GOPATH and let it tell me where it should be
Crux of the change: https://github.com/actions/setup-go/pull/47/files#diff-8cfead41d88ad47d44509a8ab0a109ad
=> add bin to path

dist/index.js, src/main.ts
output the go env inside an expando block in the logs
=> go env block

.github/workflows/versions.yml, __tests__/data/versions-manifest.json, __tests__/setup-go.test.ts, __tests__/verify-go.sh, action.yml, dist/index.js, package-lock.json, package.json, src/installer.ts, src/main.ts
This pull-request improves setup-go action to add ability to download specific version of Go from [actions/go-versions](https://github.com/actions/go-versions) releases on flight if it is not available by default.
We added intermediate step to download go from releases and current setup has the following order:
```
1. Try to find version locally
2. If it's not found locally, try to find in release manifest
3. If version is found in manifest download from releases
4. if version is not found in releases try to install from dist.
```
Additional changes:
1. Move archive extract logic to the separate function to improve readability
2. Move installation logic to common function
3. Extend test matrix in versions.yml
**Note:** unit tests are in progress.
=> Use GitHub releases to download Go versions.

README.md, dist/index.js, src/installer.ts
Recently, we have switched default branch in https://github.com/actions/go-versions to `main` and we need to switch this action too.
This fix should be integrated to tag `v2.1.0`
=> Switch manifest installation from "master" to "main" branch

.github/workflows/release-new-action-version.yml
This PR adds a workflow to automatically update tags when releasing new versions of this action, using the https://github.com/actions/publish-action action.
=> Add release action version workflow

dist/index.js, src/installer.ts
On Windows the extractor uses `tar` instead of `zip` because the code is using `os.arch()` (which returns the arch like x64 or arm64) instead of `os.platform()`.
This PR fixes this problem.
=> Fix extractor selection on windows

package-lock.json, package.json
CI is failing because of `npm audit`: https://github.com/actions/setup-go/pull/147
- Run `npm audit fix`
- Manually update Jest -- since this is a major version change, `npm audit fix` won't update this automatically
=> Fix `npm audit` issues

.github/workflows/workflow.yml
Add `cache` to workflows using `actions/setup-node`
`setup-node` GitHub Action just released a new option to add cache to steps using it.
You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
---
🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾
=> ci(workflow): add 'npm' cache for actions/setup-node in .github/workflows

README.md
Example in README.md not working
```
Can't find any online and idle self-hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-16.04'
```
=> Replace 'ubuntu-16.04' -> 'ubuntu-latest'

.github/workflows/check-dist.yml, .github/workflows/licensed.yml, .github/workflows/versions.yml, .github/workflows/workflow.yml, action.yml
Node 12 has an end of life on April 30, 2022.
This PR updates the default runtime to [node16](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/), rather then node12. 
This is supported on all Actions Runners v2.285.0 or later.
Describe your changes.
Add link to the related issue.
=> Update default runtime to node16

__tests__/setup-go.test.ts, action.yml, dist/index.js, src/installer.ts, src/main.ts, src/system.ts
In scope of this pull request we remove `stable` input and fix SemVer notation (previous 1.17.0-rc2 -> 1.17.0-rc.2). For now action needs the `stable` input to install unstable releases. In this pull request we remove the `stable` input and allow to install unstable versions without it.
**Related issue:** https://github.com/actions/setup-go/issues/191
=> Remove stable input and fix SemVer notation

__tests__/setup-go.test.ts, dist/index.js, src/main.ts
Do not export GOROOT. This has not been necessary since [Go 1.9](https://go.dev/doc/go1.9#goroot) at least (although clunky) but definitely not since [Go 1.10](https://go.dev/doc/go1.10#goroot). This is cargo culting code that is more than 2 years out of date and runs into issues when multiple go versions are used in an action run.
#107 
=> Do not export GOROOT for Go versions >= 1.9

dist/index.js, src/main.ts
io.mkdirP returns a promise that should be awaited. Without this the promise runs in the background and `addBinToPath` returns OK but then the promise errors later on.
https://github.com/actions/setup-go/issues/169
=> await io.mkdirP

.github/workflows/check-dist.yml, .github/workflows/licensed.yml, .github/workflows/versions.yml, .github/workflows/workflow.yml, README.md
- Bump some GitHub Actions
- `actions/checkout@v3`
- `actions/setup-node@v3`
- `actions/upload-artifact@v3`
- `actions/setup-go@v3` (in self examples in `README.md`)
- Removed reference to `stable` action argument - removed in #195
- **Note:** seems this has already been done.
- Added "new style" workflow build badges - generated by the GitHub web UI.
N/A
=> Bump GitHub actions, `README.md` cleanups

.gitattributes
=> Set LF for all files

__tests__/setup-go.test.ts, action.yml, dist/index.js, src/main.ts
This provides a `go-version` output from this Action to provide the version that was installed. This is useful if you specify only a partial version such as `1.15`, but need the full version installed such as `1.15.5` for later use in a workflow. This is similar to the same functionality in [actions/setup-python](https://github.com/actions/setup-python) -
https://github.com/actions/setup-python/blob/41b7212b1668f5de9d65e9c82aa777e6bbedb3a8/action.yml#L14-L16
`build.yml`:
```yaml
jobs:
test:
runs-on: ubuntu-latest
steps:
- id: setup-go
uses: action/setup-go@v2.1.4
with:
go-version: '1.15'
- name: Lookup go cache directory
run: echo "GOCACHE_DIR=$(go env GOCACHE)" >> $GITHUB_ENV
- uses: actions/cache@v2
with:
path: |
${{ env.GOCACHE_DIR }}
key: "test-${{ runner.os }}-go${{ …
```
=> Add 'go-version' Output

dist/index.js, src/main.ts
At the moment `setup-go` action has logic to create directory and add it in the runner PATH if the `go env GOPATH` command has path in output. There is no path in command output for go version < 1.7 but this command returns single byte so the condition to check `go env GOPATH` output is true for any go versions.
For example
go 1.5:
go 1.18:
This logic caused an error but it did not interrupt action on node 12 (action v2 version):
Successful run with error for go 1.5 on action v2 version: https://github.com/vsafonkin/test-repo/runs/6054892779?check_suite_focus=true#logs
After action update to node 16 (action v3 version) this error breaks the action execution.
Fixed the condition for `go env PATH` output.
Test run with go 1.18: …
=> Fix condition for GOPATH output

README.md
Added a note that the action uses pre-build binaries from Golang side.
#181 
=> Add note about golang building process

docs/adrs/0000-caching-dependencies.md
Prepare an ADR for support caching in setup-go.
=> Create ADR for integrating cache functionality to setup-go action

__tests__/setup-go.test.ts, dist/setup/index.js, src/installer.ts
Use explicit filename when downloading Windows go package.
Using the explicit filename for Windows is necessary to satisfy `Expand-Archive`'s requirement on `.zip` extension.
The solution can be seen working [here](https://github.com/buildpacks/pack/runs/7570679322?check_suite_focus=true) ([screenshot](https://user-images.githubusercontent.com/475559/181657378-24702fd4-d567-4c36-83b3-e1e6e59b0899.png)).
---
Credit goes to @redanthrax for finding the root cause. 
This PR differs from https://github.com/actions/setup-go/pull/242 in the following ways:
1. When available, uses `RUNNER_TEMP` env var similar to [tool-cache](https://github.com/actions/toolkit/blob/01e1ff7bc04e1c57c980a0d1530478a5b60cf812/packages/tool-cache/src/tool-cache.ts#L755-L759).
2. Added tests for the …
=> Use explicit filename when downloading Windows go package

README.md, action.yml, dist/setup/index.js, src/main.ts
In scope of this pull request we make available to pass GitHub token on GHES.
https://github.com/actions/runner-images-internal/issues/4479
=> Pass the token input through on GHES

dist/setup/index.js, src/installer.ts
In scope of this pull request we fix log for stable/oldstable aliases. 
=> Fix log for stable aliases

__tests__/cache-utils.test.ts, dist/cache-save/index.js, dist/setup/index.js, src/cache-utils.ts
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Issue #297 
Return early is the way of writing functions or methods so that the expected positive result is returned at the end of the function and the rest of the code terminates the execution (by returning or throwing an exception) when conditions are not met.
See [actions/cache#1012](https://github.com/actions/cache/issues/1012), [actions/setup-node#639](https://github.com/actions/setup-node/pull/639)
In `cache-utils.ts`:
**AS-IS**
```typescript
export function isCacheFeatureAvailable(): boolean {
if (!cache.isFeatureAvailable()) {
if (isGhes()) {
throw new Error(
'Cache action is only supported on GHES version >= 3.5...'
);
} else {
core.warning(
'The runner was not able to contact...'
);
}
return false;
}
return true;
}
```
**TO-BE** …
=> refactor: Use early return pattern to avoid nested conditions

__tests__/cache-utils.test.ts, dist/cache-save/index.js, dist/setup/index.js, src/cache-utils.ts
Since older versions of go (before 1.15) do not have the `GOMODCACHE` command, we must allow the cache to be built only based on the output of the `GOCACHE` command
https://github.com/actions/setup-go/issues/304
- [+] Mark if tests were added or updated to cover the changes.
=> Allow to use only GOCACHE for cache

dist/setup/index.js, src/main.ts
Now the current version will be used for caching instead of `.x`, which will allow the cache to be used more efficiently
#280
=> Use actual version in cache

dist/setup/index.js, src/main.ts
In scope of this pull request we add step warning if go-version input is empty
https://github.com/actions/setup-go/issues/83
=> Add step warning if go-version input is empty

dist/setup/index.js, src/main.ts
In scope of this pull request we update logic to add Go bin even if go-version input is empty. 
https://github.com/actions/setup-go/issues/49
=> Add Go bin if go-version input is empty

README.md
Change version of setup-go to @v4 in all samples
=> update README fo v4

.licenses/npm/@actions/cache.dep.yml, .licenses/npm/@azure/abort-controller.dep.yml, dist/cache-save/index.js, dist/setup/index.js, package-lock.json, package.json
`@actions/cache` was bumped to v3.2.1 as it appears to be slightly more performant:
| | |
| ------------------------- | --------------------------------------- |
| Benchmarked package | [iris](https://github.com/kataras/iris) |
| Cache size | ~330Mb |
| Hash | cd704a0284e7360c80bb4d50030226c684afefd87f4dd77b80ce00fe371023d2 |
| @actions/cache version \| run # | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | sum | avg | dev |
| ------ | - | - | - | - | - | - | - | - | - | - | ----- | --- | - |
| 3.0.0 (current) | 16 | 14 | 13 | 15 | 18 | 12 | 17 | 17 | 12 | 19 | 153 | 15.3 | ~2.3 |
| 3.2.1 | 10 | 14 | 8 | 8 | 9 | 7 | 8 | 7 | 8 | 8 |  87 | 8.7 | ~2.0 |  
**Related issue:** https://github.com/actions/setup-go/issues/372
=> Bump @actions/cache dependency to v3.2.1

README.md
In scope of this pull request we add note about YAML parsing versions like `1.20`.
https://github.com/actions/setup-go/issues/380
=> Add note about YAML parsing versions

dist/setup/index.js, src/cache-restore.ts
Cache key now contains the os version in order to avoid conflicts between the binaries built against the unexpected libraries
TBD: the original issue explicitly mentions Linux as the os having issue. Probably the solution should be limited to Linux only.
[link to the related issue.](https://github.com/actions/setup-go/issues/368)
=> Add imageOS to primaryKey

.github/workflows/windows-validation.yml, __tests__/setup-go.test.ts, __tests__/windows-performance.test.ts, __tests__/windows-toolcache.test.ts, dist/setup/index.js, src/installer.ts
In order to avoid slow IO of C: drive the go executables are cached to D: drive instead of C: drive and create a link (junction) from an expected location (c:\hostedtoolcache) to the actual  (D:\hostedtoolcache). 
[Original issue](https://github.com/actions/setup-go/issues/240)
[Investigation issue](https://github.com/actions/runner-images-internal/discussions/5143)
=> Fix Install on Windows is very slow

.github/workflows/windows-validation.yml, dist/setup/index.js, src/installer.ts
This change ensures that we symlink not only the tool directory but also the completion marker when adding `go` to the hosted tool cache on Windows.
Not raised, but without this change it is impossible to run the action twice with the same `go-version` input on Windows because the second run fails with errors related to files already existing.
**Testing:**
- 🔴 Example test run without the fix: https://github.com/galargh/setup-go/actions/runs/5843165063/job/15845040764
- 🟢 Example test run with the fix: https://github.com/galargh/setup-go/actions/runs/5843616834/job/15845918944
=> Fix hosted tool cache usage on windows

README.md
Just a highlighting that `cache-dependency-path` parameter can accept multiple files and can handle wildcards + example.
https://github.com/actions/setup-go/issues/371
=>  Improve documentation regarding dependencies caching

.github/workflows/versions.yml, .github/workflows/windows-validation.yml, README.md, action.yml, docs/adrs/0000-caching-dependencies.md
Node12 was deleted from runner. Node20 was added to Actions Runner on v2.308.0.
Node16 has en end of life on 11 Sep 2023.
This PR updates the default runtime to node20, rather then node16
relates to https://github.com/actions/runner/pull/2732
N/A
---
needs a major version bump after the PR merge
=> feat: upgrade to use node 20 runtime and bump checkout action to v4

README.md
- docs: bump `actions/setup-go` to v5, followup with v5 release
Add link to the related issue.
=> docs: bump `actions/setup-go` to v5

README.md
Add info about the v5 release to the README.md
Previously, users would think that v4 was the latest version if the only skimmed the bold headlines in the README.
=> Update README.md with V5 release notes

README.md, docs/contributors.md
Starting from Go 1.21, the go.mod file now includes patch versions as well.
```
$ go1.21.0 mod init test
go: creating new go.mod: module test
$ cat go.mod
module test
go 1.21.0
```
This is explained in the official Go documentation.
> Go 1.21 introduces a small change to the numbering of releases. In the past, we used Go 1.N to refer to both the overall Go language version and release family as well as the first release in that family. Starting in Go 1.21, the first release is now Go 1.N.0. Today we are releasing both the Go 1.21 language and its initial implementation, the Go 1.21.0 release. These notes refer to “Go 1.21”; tools like go version will report “go1.21.0” (until you upgrade to Go 1.21.1). See “[Go versions](https://go.dev/doc/toolchain#version)” in the “Go …
=> Remove the description of the old go.mod specification

dist/setup/index.js, src/cache-restore.ts
GitHub has added the arm64 runner, so arch should be used as part of the cache key. Otherwise, if there are `macos-13` `macos-14` running at the same time, the late executor will get the wrong cache.
https://github.com/actions/setup-python/pull/896
=> fix: add arch to cache key

.github/workflows/release-new-action-version.yml, .github/workflows/versions.yml, package-lock.json
- Update the Validate 'setup-go' workflow to include macos-13 and refreshed local-cache versions to align with the latest platform capabilities and performance enhancements.
- Upgrade the actions/publish-action to version @v0.3.0
- Bump [micromatch](https://github.com/micromatch/micromatch) from 4.0.5 to 4.0.8
N/A
=> Enhance workflows and Upgrade micromatch Dependency

README.md, __tests__/setup-go.test.ts, dist/setup/index.js, package-lock.json, src/installer.ts
This PR leverages the raw endpoint (https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json) to retrieve the golang manifest as a fallback mechanism. This allows GitHub Actions Runners, which have no API token and exceed the anonymous rate limit of 60 requests/hour/IP to still retrieve the manifest list without needing credentials.
This is especially helpful for GitHub Enterprise Server and self-hosted runners, as there multiple runners might share the same IP-address and quickly exceed the available rate limit. Supplying an access token for github.com is cumbersome, as it requires another technical user and the secret isn't exposed to forks, preventing builds from forks.
The implementation as a fallback mechanism minimizes the risk of breaking …
=> feat: fallback to "raw" endpoint for manifest when rate limit is reached

.licenses/npm/undici.dep.yml, __tests__/utils.test.ts, dist/cache-save/index.js, dist/setup/index.js, package-lock.json, src/installer.ts, src/utils.ts
This PR includes the following updates:
- Update the validation logic for self-hosted environments to ensure accurate detection and handling of self-hosted setups.
- Bump [undici](https://github.com/nodejs/undici) from 5.28.4 to 5.28.5.
#550 
=> Update self-hosted environment validation and bump undici version

.github/workflows/publish-immutable-actions.yml
This workflow file publishes new action releases to the immutable action package of the same name as this repo.
This is part of the Immutable Actions project which is not yet fully released to the public. First party actions like this one are part of our initial testing of this feature.
=> V3 - Add workflow file for publishing releases to immutable action package

dist/setup/index.js, src/installer.ts
This fix ensures proper validation of the manifest before processing and improves error handling by falling back to a secondary source for unexpected manifest structures.
#580
=> Add manifest validation and improve error handling

README.md, __tests__/setup-go.test.ts, dist/setup/index.js, src/installer.ts, src/main.ts
- Configure environment to avoid toolchain installs
Force `go` to always use the local toolchain (i.e. the one the one that
shipped with the go command being run) via setting the `GOTOOLCHAIN`
environment variable to `local`[1]:
> When GOTOOLCHAIN is set to local, the go command always runs the
bundled Go toolchain.
This is how things are setup in the official Docker images (e.g.[2], see
also the discussion around that change[3]). The motivation behind this
is to:
* Reduce duplicate work, the action will install a version of Go, a
toolchain will be detected, the toolchain will be detected and then
another version of Go installed[4]
* Avoid Unexpected behaviour: if you specify this action runs with some Go
version (e.g. `1.21.0`) but your go.mod contains a `toolchain` or `go`
directive for …
=> Improve toolchain handling
